name: Deploy

on:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
env:
  ZOLA_VERSION: 0.17.2
  WORKING_DIRECTORY: src

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Get zola
        run: |
          wget -q -O - \
          "https://github.com/getzola/zola/releases/download/v${{ env.ZOLA_VERSION }}/zola-v${{ env.ZOLA_VERSION }}-x86_64-unknown-linux-gnu.tar.gz" \
          | tar xzf - -C /usr/local/bin

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: zola build

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
